# Generated by Django 5.0.14 on 2026-08-25 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('socios', '0006_socio_codigo_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='asociacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administradores', to='core.asociacion'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('superadministrador', 'Superadministrador'), ('administrador_asociacion', 'Administrador de Asociacion'), ('administrador_conjunto', 'Administrador de Conjunto'), ('miembro', 'Miembro')], default='miembro', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='conjunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administradores', to='core.conjunto'),
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('castigado', 'Castigado'), ('baja', 'Dado de baja')], default='activo', max_length=20)),
                ('estado_pago', models.CharField(choices=[('al_dia', 'Al día'), ('con_deuda', 'Con deuda')], default='al_dia', max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('antiguedad', models.PositiveIntegerField(default=0, verbose_name='Antigüedad (años)')),
                ('observacion', models.TextField(blank=True, default='')),
                ('asociacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='core.asociacion')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='socios.socio')),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='core.conjunto')),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.AddConstraint(
            model_name='membresia',
            constraint=models.UniqueConstraint(fields=('socio', 'asociacion', 'conjunto'), name='unique_membresia_socio_conjunto'),
        ),
    ]
