# Generated by Django 5.0.14 on 2026-08-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('socios', '0007_userprofile_grupo_userprofile_rol_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membresia',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'baja'), _negated=True), fields=('socio', 'grupo'), name='unique_membresia_vigente_por_grupo'),
        ),
    ]
