# Generated by Django 5.0.14 on 2026-08-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0008_membresia_unique_membresia_vigente_por_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='modalidad',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Categoría o modalidad'),
        ),
        migrations.AddField(
            model_name='socio',
            name='sexo',
            field=models.CharField(blank=True, choices=[('m', 'Varón'), ('f', 'Mujer'), ('otro', 'Otro')], default='', max_length=10),
        ),
    ]
