# Generated by Django 5.0.14 on 2026-09-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0012_socio_creado_por_membresia_bloque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socio',
            options={'ordering': ['-fecha_ingreso', 'apellido_paterno', 'apellido_materno', 'nombre'], 'verbose_name': 'Socio', 'verbose_name_plural': 'Socios'},
        ),
        migrations.RemoveField(
            model_name='socio',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='modalidad',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='razon',
        ),
    ]
