# Generated by Django 5.0.14 on 2026-09-04 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('danzarines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha_evento', models.DateField(verbose_name='Fecha del evento')),
                ('lugar', models.CharField(blank=True, default='', max_length=250)),
                ('activo', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('finalizado', 'Finalizado')], default='programado', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('asociacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='core.asociacion')),
                ('conjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='core.conjunto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha_evento', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='certificados/')),
                ('generado', models.DateTimeField(auto_now_add=True)),
                ('danzarin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='danzarines.danzarin')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='EventoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrado', models.DateTimeField(auto_now_add=True)),
                ('danzarin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='danzarines.danzarin')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='eventos.evento')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(related_name='eventos', through='eventos.EventoParticipante', to='danzarines.danzarin'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.UniqueConstraint(fields=('evento', 'danzarin'), name='unique_certificado_evento_danzarin'),
        ),
        migrations.AddConstraint(
            model_name='eventoparticipante',
            constraint=models.UniqueConstraint(fields=('evento', 'danzarin'), name='unique_participante_evento'),
        ),
    ]
