# Generated by Django 5.0.14 on 2026-08-25 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('eventos', '0001_initial'),
        ('socios', '0007_userprofile_grupo_userprofile_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('finalizado', 'Finalizado')], default='programado', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='core.grupo'),
        ),
        migrations.AddField(
            model_name='evento',
            name='subgrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='core.subgrupo'),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='certificados/')),
                ('generado', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='eventos.evento')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='socios.socio')),
            ],
        ),
        migrations.CreateModel(
            name='EventoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrado', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='eventos.evento')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='socios.socio')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(related_name='eventos', through='eventos.EventoParticipante', to='socios.socio'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.UniqueConstraint(fields=('evento', 'socio'), name='unique_certificado_evento_socio'),
        ),
        migrations.AddConstraint(
            model_name='eventoparticipante',
            constraint=models.UniqueConstraint(fields=('evento', 'socio'), name='unique_participante_evento'),
        ),
    ]
