# Generated by Django 5.0.14 on 2026-09-04 15:18

from datetime import date

from django.db import migrations, models


def copiar_fechas_existentes(apps, schema_editor):
    Evento = apps.get_model('eventos', 'Evento')
    for evento in Evento.objects.all().iterator():
        fecha = evento.fecha_evento or date.today()
        Evento.objects.filter(pk=evento.pk).update(
            fecha_inicio=evento.fecha_inicio or fecha,
            fecha_fin=evento.fecha_fin or evento.fecha_inicio or fecha,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_options_evento_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-fecha_inicio', 'nombre'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RunPython(copiar_fechas_existentes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='evento',
            name='fecha_evento',
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
    ]
