# Generated by Django 5.0.14 on 2026-08-25 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_migrar_datos_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='asociacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='core.asociacion'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='conjunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='core.conjunto'),
        ),
    ]
