# Generated by Django 5.0.14 on 2026-09-04 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('danzarines', '0001_initial'),
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='souvenirs/')),
                ('stock', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('asociacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='souvenirs', to='core.asociacion')),
                ('conjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='souvenirs', to='core.conjunto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='souvenirs_creados', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='souvenirs', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Souvenir',
                'verbose_name_plural': 'Souvenirs',
            },
        ),
        migrations.CreateModel(
            name='SouvenirEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(auto_now_add=True, verbose_name='Fecha de entrega')),
                ('observacion', models.TextField(blank=True, default='', verbose_name='Observación')),
                ('danzarin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_souvenir', to='danzarines.danzarin')),
                ('entregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_souvenir', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entregas_souvenir', to='eventos.evento')),
                ('souvenir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='souvenirs.souvenir')),
            ],
            options={
                'verbose_name': 'Entrega de souvenir',
                'verbose_name_plural': 'Entregas de souvenirs',
                'ordering': ['-fecha_entrega'],
            },
        ),
    ]
