# Generated by Django 5.0.14 on 2026-09-01 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_renombrar_esquema_asociaciones_conjuntos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='core.conjunto')),
            ],
            options={
                'ordering': ['conjunto__asociacion__nombre', 'conjunto__nombre', 'nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='bloque',
            constraint=models.UniqueConstraint(fields=('conjunto', 'nombre'), name='unique_bloque_por_conjunto'),
        ),
    ]
