# Generated by Django 5.0.14 on 2026-09-04 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloques', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Danzarin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_danzarin', models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Código de danzarin')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(blank=True, default='', max_length=150, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, default='', max_length=150, verbose_name='Apellido materno')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('carnet_ci', models.CharField(blank=True, default='', max_length=30, verbose_name='CI / Carnet')),
                ('carnet_complemento', models.CharField(blank=True, default='', max_length=20, verbose_name='Complemento CI')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('ciudad', models.CharField(blank=True, default='', max_length=150, verbose_name='Ciudad')),
                ('direccion', models.CharField(blank=True, default='', max_length=250, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(blank=True, choices=[('m', 'Varón'), ('f', 'Mujer'), ('otro', 'Otro')], default='', max_length=10)),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('recibio_souvenir', models.BooleanField(default=False, verbose_name='Recibió souvenir')),
                ('observacion', models.TextField(blank=True, default='', verbose_name='Observación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danzarines_creados', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='danzarin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Danzarin',
                'verbose_name_plural': 'Danzarines',
                'ordering': ['-fecha_ingreso', 'apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('castigado', 'Castigado'), ('baja', 'Dado de baja')], default='activo', max_length=20)),
                ('estado_pago', models.CharField(choices=[('al_dia', 'Al día'), ('con_deuda', 'Con deuda')], default='al_dia', max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('antiguedad', models.PositiveIntegerField(default=0, verbose_name='Antigüedad (años)')),
                ('observacion', models.TextField(blank=True, default='')),
                ('asociacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='core.asociacion')),
                ('bloque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='bloques.bloque')),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='core.conjunto')),
                ('danzarin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='danzarines.danzarin')),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('rol', models.CharField(choices=[('superadministrador', 'Superadministrador'), ('administrador_asociacion', 'Administrador de Asociacion'), ('administrador_conjunto', 'Administrador de Conjunto'), ('miembro', 'Miembro')], default='miembro', max_length=30)),
                ('asociacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administradores', to='core.asociacion')),
                ('conjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administradores', to='core.conjunto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
        migrations.AddConstraint(
            model_name='membresia',
            constraint=models.UniqueConstraint(fields=('danzarin', 'asociacion', 'conjunto'), name='unique_membresia_danzarin_conjunto'),
        ),
        migrations.AddConstraint(
            model_name='membresia',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'baja'), _negated=True), fields=('danzarin', 'asociacion'), name='unique_membresia_vigente_por_asociacion'),
        ),
    ]
