# Generated by Django 5.2.17 on 2026-09-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danzarines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='danzarin',
            name='antiguedad_observacion',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Observación de antigüedad'),
        ),
        migrations.AddField(
            model_name='danzarin',
            name='fecha_ingreso_grupo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso al grupo'),
        ),
    ]
