# Generated by Django 5.2.17 on 2026-09-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danzarines', '0002_danzarin_antiguedad_observacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danzarin',
            name='codigo_danzarin',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Código de danzarin'),
        ),
    ]
